hazelcast:
  cluster-name: dev
  instance-name: users-app1
  network:
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: true
        member-list:
          - host.docker.internal

